var sortKey = require('./index.js').sortKey
var assert = require('assert')

assert(sortKey('') < sortKey('abc'))
assert(sortKey('a') < sortKey('abc'))
assert(sortKey('ab') < sortKey('abc'))
assert(sortKey('abc') < sortKey('def'))
assert(sortKey('') < sortKey([]))
assert(sortKey('') < sortKey(['abc']))
assert(sortKey('abc') < sortKey(['abc']))
assert(sortKey([]) < sortKey(['abc']))
assert(sortKey(['abc']) < sortKey(['abc', 'def']))
assert(sortKey(['abc', 'abc']) < sortKey(['abc', 'def']))
assert(sortKey(['abc', '']) < sortKey(['abc', 'abc']))
assert(sortKey(['abc', 'a']) < sortKey(['abc', 'abc']))
assert(sortKey(['abc', 'ab']) < sortKey(['abc', 'abc']))
assert(sortKey(['abc', '']) < sortKey(['abc', []]))
assert(sortKey(['abc', '']) < sortKey(['abc', [[]]]))
assert(sortKey(['abc', '']) < sortKey(['abc', ['abc']]))
assert(sortKey(['abc', 'a']) < sortKey(['abc', ['abc']]))
assert(sortKey(['abc', 'ab']) < sortKey(['abc', ['abc']]))
assert(sortKey(['abc', 'abc']) < sortKey(['abc', ['abc']]))
assert(sortKey(['abc', 'abcdef']) < sortKey(['abc', ['abc']]))
assert(sortKey(['abc', 'abc']) < sortKey(['abc', ['def']]))
assert(sortKey(['abc', 'abcdef']) < sortKey(['abc', ['def']]))
assert(sortKey(['abc', '']) < sortKey(['abc', ['abc'], ['abc']]))
assert(sortKey(['abc', 'a']) < sortKey(['abc', ['abc'], ['abc']]))
assert(sortKey(['abc', 'ab']) < sortKey(['abc', ['abc'], []]))
assert(sortKey(['abc', 'ab']) < sortKey(['abc', ['abc'], ['abc']]))
assert(sortKey(['abc', []]) < sortKey(['abc', ['abc']]))
assert(sortKey(['abc', ['a']]) < sortKey(['abc', ['abc']]))
assert(sortKey(['abc', ['ab']]) < sortKey(['abc', ['abc']]))
assert(sortKey(['abc', ['ab'], []]) < sortKey(['abc', ['abc']]))
assert(sortKey(['abc', ['ab']]) < sortKey(['abc', ['abc'], []]))
